### ISSUE TITLE
Cannot connect to the server

### ISSUE THREAD

**Issue by DanChaltiel** [Aypak/shiny_server_rpi4#1]
Hi Aypak,

Thank you very much for sharing this code.
I ran your script on a brand new and up-to-date raspberry pi 4 and everything went alright, but I cannot connect to http://<my-raspi4-address>:3838/sample-apps/hello/: the browser shows an `ERR_CONNECTION_REFUSED`.
Folder `/var/log/shiny-server` is empty and checking status outputs this:

```console
pi@raspberrypi4:~ $ sudo systemctl status shiny-server
● shiny-server.service - ShinyServer
   Loaded: loaded (/lib/systemd/system/shiny-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-10-24 11:40:45 CEST; 31s ago
  Process: 31131 ExecStart=/usr/bin/shiny-server (code=exited, status=0/SUCCESS)
  Process: 31133 ExecStopPost=/usr/bin sleep 5 (code=exited, status=203/EXEC)
 Main PID: 31131 (code=exited, status=0/SUCCESS)

oct. 24 11:40:45 raspberrypi4 systemd[1]: shiny-server.service: Service RestartSec=1s expired, scheduling restart.
oct. 24 11:40:45 raspberrypi4 systemd[1]: shiny-server.service: Scheduled restart job, restart counter is at 3.
oct. 24 11:40:45 raspberrypi4 systemd[1]: Stopped ShinyServer.
oct. 24 11:40:45 raspberrypi4 systemd[1]: shiny-server.service: Start request repeated too quickly.
oct. 24 11:40:45 raspberrypi4 systemd[1]: shiny-server.service: Failed with result 'exit-code'.
oct. 24 11:40:45 raspberrypi4 systemd[1]: Failed to start ShinyServer.
```

`sudo systemctl restart shiny-server` fails with the same kind of message.

Would you have any idea of how could I make it work?

Thanks a lot

EDIT: ok I get it, `pi@raspberrypi4:~ $ journalctl -u shiny-server` says `shiny-server.service: Failed to execute command: Permission denied`. It seems that this is a permission issue but I'm not sure how to solve it yet since I already use `sudo`.

**Comment by Aypak** [comment]
Hi @DanChaltiel ,
It looks like a permissions issue with either `/lib/systemd/system/shiny-server.service` or `/usr/bin/shiny-server`. The permissions on these files should be 644 and 777 respectively. Kindly share the details of the Raspberry Pi and operating system you are using, and the contents of `/lib/systemd/system/shiny-server.service`

**Comment by DanChaltiel** [comment]
Here is the detail:

```console
pi@raspberrypi4:~ $ ls -l /lib/systemd/system/shiny-server.service
-rw-r--r-- 1 root root 282 oct.  23 16:15 /lib/systemd/system/shiny-server.service
pi@raspberrypi4:~ $ ls -l /usr/bin/shiny-server
lrwxrwxrwx 1 root root 40 oct.  23 16:15 /usr/bin/shiny-server -> /usr/local/shiny-server/bin/shiny-server
pi@raspberrypi4:~ $ uname -a
Linux raspberrypi4 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
pi@raspberrypi4:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
pi@raspberrypi4:~ $ cat /lib/systemd/system/shiny-server.service
[Unit]
Description=ShinyServer

[Service]
Type=simple
ExecStart=/usr/bin/shiny-server
KillMode=process
ExecReload=/usr/bin kill -HUP $MAINPID
ExecStopPost=/usr/bin sleep 5
Restart=on-failure
RestartSec=1
StartLimitInterval=45
StartLimitBurst=3

[Install]
WantedBy=multi-user.target
```

Thanks a lot for your help

**EDIT:** For the sake of testing, I've put `/lib/systemd/system/shiny-server.service`, `/usr/bin/shiny-server`, and `/usr/local/shiny-server/bin/shiny-server` to 777. It didn't make any difference after `sudo systemctl restart shiny-server`.

**Comment by Aypak** [comment]
Thanks for sharing the details above. I was able to replicate the problem. 
It was due to a node execution error. The installation script was intended to work on [Ubuntu 20 for raspberry pi](https://cdimage.ubuntu.com/releases/20.04.1/release/ubuntu-20.04.1-preinstalled-server-arm64+raspi.img.xz). But because you're using Raspbian Buster, you need to use the armv7l version of node instead of arm64. I've created a branch called armv71, which should work on Raspbian. Kindly do the following (assuming you have already cloned 
`shiny_server_rpi4` in your home directory):
- Remove shiny-server from `/usr/bin` if it exists - `sudo rm /usr/bin/shiny-server`
- Clone the shiny-server repo into the home directory - `git clone https://github.com/rstudio/shiny-server.git`
- Switch to the arm71 branch of this repo and pull the latest changes- `cd ~/shiny_server_rpi4 && git fetch --all && git checkout armv71 && git pull`
- Copy the install_node script to shiny-server - `cp ~/shiny_server_rpi4/stable_support_files/install-node.sh ~/shiny-server/external/node/`
- Create the package and run all other steps
```
~/shiny-server/packaging/make-package.sh

## Copy Shiny Server directory to system location
sudo cp -r ~/shiny-server/ /usr/local/

# Place a shortcut to the shiny-server executable in /usr/bin
sudo ln -s /usr/local/shiny-server/bin/shiny-server /usr/bin/shiny-server

#Create shiny user. On some systems, you may need to specify the full path to 'useradd'
sudo useradd -r -m shiny

# Create log, config, and application directories
sudo mkdir -p /var/log/shiny-server
sudo mkdir -p /srv/shiny-server
sudo mkdir -p /var/lib/shiny-server
sudo chown shiny /var/log/shiny-server
sudo mkdir -p /etc/shiny-server

# Return to Shiny Server directory and set shiny-server.conf
cd ~/shiny-server || return
sudo cp config/default.config /etc/shiny-server/shiny-server.conf
sudo cp -r /usr/local/shiny-server/ext/pandoc .
sudo rm -r /usr/local/shiny-server/ext/pandoc/
# Setup for start at boot: http://docs.rstudio.com/shiny-server/#systemd-redhat-7-ubuntu-15.04-sles-12
# and: https://www.raspberrypi-spy.co.uk/2015/10/how-to-autorun-a-python-script-on-boot-using-systemd/
sed -i -e "s:ExecStart=/usr/bin/env bash -c 'exec /opt/shiny-server/bin/shiny-server >> /var/log/shiny-server.log 2>&1':ExecStart=/usr/bin/shiny-server:g"  config/systemd/shiny-server.service
sed -i -e 's:/env::'  config/systemd/shiny-server.service
sudo cp config/systemd/shiny-server.service /lib/systemd/system/
sudo chmod 644 /lib/systemd/system/shiny-server.service
sudo systemctl daemon-reload
sudo systemctl enable shiny-server.service

# Final Shiny Server Setup
sudo cp samples/welcome.html /srv/shiny-server/index.html
sudo cp -r samples/sample-apps/ /srv/shiny-server/

# Restart the shiny service
cd  || return & sudo service shiny-server restart
```
Hope this helps!

**Comment by DanChaltiel** [comment]
Wow, I was not expecting so much, thank you very much!

However, when running `~/shiny-server/packaging/make-package.sh`, it ends with an error:

```console
[...]
<other things, like downloading>
[...]
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/shiny-server/packaging/build
+ make
Scanning dependencies of target shiny-server
[ 50%] Building CXX object src/CMakeFiles/shiny-server.dir/launcher.cc.o
[100%] Linking CXX executable ../../../bin/shiny-server
[100%] Built target shiny-server
+ pushd ../..
~/shiny-server ~/shiny-server/packaging/build
+ ./external/node/install-node.sh
Downloading Node 12.15.0 from https://nodejs.org/dist/v12.15.0/node-v12.15.0-linux-arm64.tar.xz
--2020-10-25 22:12:57--  https://nodejs.org/dist/v12.15.0/node-v12.15.0-linux-arm64.tar.xz
Résolution de nodejs.org (nodejs.org)… 2606:4700:10::6814:172e, 2606:4700:10::6814:162e, 104.20.22.46, ...
Connexion à nodejs.org (nodejs.org)|2606:4700:10::6814:172e|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 13695552 (13M) [application/x-xz]
Sauvegarde en : « /tmp/node-v12.15.0-linux-arm64.tar.xz »

/tmp/node-v12.15.0-linux-arm64.tar.xz                       100%[========================================================================================================================================>]  13,06M  4,15MB/s    ds 3,1s

2020-10-25 22:13:00 (4,15 MB/s) — « /tmp/node-v12.15.0-linux-arm64.tar.xz » sauvegardé [13695552/13695552]

Extracting node-v12.15.0-linux-arm64.tar.xz
+ ./bin/npm install --production
./bin/npm: 4: exec: ./bin/../ext/node/bin/node: Exec format error
```

This issue (https://github.com/rstudio/shiny-server/issues/347) seems related. 
It might come from the x64 architecture, so I might want to change the version in `~/shiny-server/external/node/install-node.sh`.
There are versions specific to the Raspberry Pi in older releases of nodejs (such as https://nodejs.org/dist/v0.10.9/) but I couldn't find one for newer versions.
However, RPI4 seems to be ARMv8 ([link](https://www.makersupplies.sg/blogs/tutorials/how-to-install-node-js-and-npm-on-the-raspberry-pi)) so it should have worked.
Also, I wondered, why not use `sudo apt install nodejs` instead of building it myself?

**Comment by Aypak** [comment]
Hi @DanChaltiel ,
I think you're right. The problem is architecture related. I recommend that you use [nvm](https://github.com/nvm-sh/nvm#usage) to install node version 12 (I'm not sure if it will work with later versions of node) :
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash

# exit and reopen your terminal session

nvm install 12
```
- Change the node version in ~/shiny-server/external/node/install-node.sh to the version that is installed by nvm

- Then run all the steps after cloning the shiny-server repo:
```
~/shiny-server/packaging/make-package.sh

## Copy Shiny Server directory to system location
sudo cp -r ~/shiny-server/ /usr/local/

# Place a shortcut to the shiny-server executable in /usr/bin
sudo ln -s /usr/local/shiny-server/bin/shiny-server /usr/bin/shiny-server

#Create shiny user. On some systems, you may need to specify the full path to 'useradd'
sudo useradd -r -m shiny

# Create log, config, and application directories
sudo mkdir -p /var/log/shiny-server
sudo mkdir -p /srv/shiny-server
sudo mkdir -p /var/lib/shiny-server
sudo chown shiny /var/log/shiny-server
sudo mkdir -p /etc/shiny-server

# Return to Shiny Server directory and set shiny-server.conf
cd ~/shiny-server || return
sudo cp config/default.config /etc/shiny-server/shiny-server.conf
sudo cp -r /usr/local/shiny-server/ext/pandoc .
sudo rm -r /usr/local/shiny-server/ext/pandoc/
# Setup for start at boot: http://docs.rstudio.com/shiny-server/#systemd-redhat-7-ubuntu-15.04-sles-12
# and: https://www.raspberrypi-spy.co.uk/2015/10/how-to-autorun-a-python-script-on-boot-using-systemd/
sed -i -e "s:ExecStart=/usr/bin/env bash -c 'exec /opt/shiny-server/bin/shiny-server >> /var/log/shiny-server.log 2>&1':ExecStart=/usr/bin/shiny-server:g"  config/systemd/shiny-server.service
sed -i -e 's:/env::'  config/systemd/shiny-server.service
sudo cp config/systemd/shiny-server.service /lib/systemd/system/
sudo chmod 644 /lib/systemd/system/shiny-server.service
sudo systemctl daemon-reload
sudo systemctl enable shiny-server.service

# Final Shiny Server Setup
sudo cp samples/welcome.html /srv/shiny-server/index.html
sudo cp -r samples/sample-apps/ /srv/shiny-server/

# Restart the shiny service
cd  || return & sudo service shiny-server restart
```

**Comment by DanChaltiel** [comment]
OK I figured it out when you were replying. There was a little typo in your previous response (arm71 instead of arm7l). It's a shame that they use such error-prone names.
I didn't see the error message, drown in the console, my bad.

Anyway, this installed nodejs with no errors (a few warnings though), and it worked like a charm.

Thank you so much!

**Comment by Aypak** [comment]
Glad I was able to help. I'll come up with a more permanent fix to account for architecture differences
